PIC24 Support Libraries: ESOS_Task_Sensor_Service
ESOS_Task_Sensor_Service
Files
file esos_sensor.h
file esos_hwxxx_sensor.h
This file contains routines which configure and use sensors on the Microchip PIC24 MCUs.
file esos_hwxxx_sensor.c
Enumerations
enum esos_sensor_ch_t
enum esos_sensor_vref_t
enum esos_sensor_process_t
enum esos_sensor_format_t
Functions
ESOS_CHILD_TASK (_WAIT_ON_AVAILABLE_SENSOR, esos_sensor_ch_t, esos_sensor_vref_t)
ESOS_CHILD_TASK (_WAIT_SENSOR_QUICK_READ, uint16_t *u16_data)
ESOS_CHILD_TASK (_WAIT_SENSOR_READ, uint16_t *u16_data, uint8_t, esos_sensor_format_t)
BOOL ESOS_SENSOR_CLOSE (void)
void esos_sensor_config_hw (esos_sensor_ch_t, esos_sensor_vref_t)
void esos_sensor_initiate_conversion_hw (void)
uint16_t esos_sensor_getvalue_u16_hw (void)
void esos_sensor_release_hw (void)
BOOL esos_sensor_is_converting_hw (void)
Detailed Description
Enumeration Type Documentation
esos_sensor_ch_t
enum esos_sensor_ch_t
enumeration to select sensor channel
Definition at line 52 of file esos_sensor.h.
esos_sensor_format_t
enum esos_sensor_format_t
enumeration to select sensor return value format
Definition at line 120 of file esos_sensor.h.
esos_sensor_process_t
enum esos_sensor_process_t
enumeration to select sensor processing
Definition at line 89 of file esos_sensor.h.
esos_sensor_vref_t
enum esos_sensor_vref_t
enumeration to select sensor voltage reference
Definition at line 74 of file esos_sensor.h.
Function Documentation
ESOS_CHILD_TASK() [1/3]
ESOS_CHILD_TASK (_WAIT_ON_AVAILABLE_SENSOR , esos_sensor_ch_t e_senCh, esos_sensor_vref_t e_senVRef)
Waits until a sensor is available.
Parameters
e_senCh enumeration to select sensor channel
e_senVRef enumeration to select sensor voltage reference
Definition at line 42 of file esos_sensor.c.
ESOS_CHILD_TASK() [2/3]
ESOS_CHILD_TASK (_WAIT_SENSOR_QUICK_READ , uint16_t * pu16_data)
Waits until a sensor is read (quick version).
Parameters
pu16_data pointer to the location of the resulting data
Definition at line 62 of file esos_sensor.c.
ESOS_CHILD_TASK() [3/3]
ESOS_CHILD_TASK (_WAIT_SENSOR_READ , uint16_t * pu16_data, uint8_t e_senProcess, esos_sensor_format_t e_senFMT)
Waits until a sensor is read (extended version).
Parameters
pu16_data pointer to the resultant data
e_senProcess enumeration of type of processing to be completed
e_senFMT enumeration of the format of the resultant data
Definition at line 132 of file esos_sensor.c.
ESOS_SENSOR_CLOSE()
BOOL ESOS_SENSOR_CLOSE (void)
Waits until a sensor is closed.
Definition at line 387 of file esos_sensor.c.
esos_sensor_config_hw()
void esos_sensor_config_hw (esos_sensor_ch_t e_senCh, esos_sensor_vref_t e_senVRef)
Configure and enable the sensor module for hwxxx hardware.
Parameters
e_senCh specifies sensor channel
e_senVRef specifies sensor voltage reference
Definition at line 54 of file esos_hwxxx_sensor.c.
esos_sensor_getvalue_u16_hw()
uint16_t esos_sensor_getvalue_u16_hw (void)
Receive the value from a conversion that has already been initiated
Definition at line 81 of file esos_hwxxx_sensor.c.
Referenced by ESOS_CHILD_TASK().
esos_sensor_initiate_conversion_hw()
void esos_sensor_initiate_conversion_hw (void)
Initiate a conversion for a configured sensor
Definition at line 72 of file esos_hwxxx_sensor.c.
esos_sensor_is_converting_hw()
BOOL esos_sensor_is_converting_hw (void)
Determine truth of: the sensor is currently converting
Definition at line 63 of file esos_hwxxx_sensor.c.
Referenced by ESOS_CHILD_TASK().
esos_sensor_release_hw()
void esos_sensor_release_hw (void)
Release any pending conversions for the sensor
Definition at line 90 of file esos_hwxxx_sensor.c.
Referenced by ESOS_SENSOR_CLOSE().